In [7]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

In [3]:
df = pd.read_csv(r"C:\Posting\Medical Cost Linear Regression\medical_cost.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Id        1338 non-null   int64
 1   age       1338 non-null   int64
 2   sex       1338 non-null   object
 3   bmi       1338 non-null   float64
 4   children  1338 non-null   int64
 5   smoker    1338 non-null   object
 6   region    1338 non-null   object
 7   charges   1338 non-null   float64
dtypes: float64(2), int64(3), object(3)
memory usage: 83.8+ KB

In [2]:
df.describe()

                Id          age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000  1338.000000   1338.000000
mean    669.500000    39.207025    30.663397     1.094918  13270.422265
std     386.391641    14.049960     6.098187     1.205493  12110.011237
min       1.000000    18.000000    15.960000     0.000000   1121.873900
25%     335.250000    27.000000    26.296250     0.000000   4740.287150
50%     669.500000    39.000000    30.400000     1.000000   9382.033000
75%    1003.750000    51.000000    34.693750     2.000000  16639.912515
max    1338.000000    64.000000    53.130000     5.000000  63770.428010

In [5]:
df.isnull().sum()

Id          0
age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [12]:
le = LabelEncoder()
df["sex"] = le.fit_transform(df["sex"])
df["smoker"] = le.fit_transform(df["smoker"])
df["region"] = le.fit_transform(df["region"])

In [14]:
x = df[["age", "sex", "bmi", "children", "smoker", "region"]]
y = df["charges"]

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 42)

764      9095.06825
887      5272.17580
890     29330.98315
1293     9301.89355
259     33750.29180
           ...
109     47055.53210
575     12222.89830
535      6067.12675
543     63770.42801
846      9872.70100
Name: charges, Length: 268, dtype: float64

In [21]:
lr = LinearRegression()
lr.fit(x_train, y_train)
y_pred = lr.predict(x_test)
y_pred

array([ 9176.38574692,  7227.99834449, 37308.87604238,  9760.91934213,
       27237.20072471, 10715.77675377,   399.31843855, 17014.22717985,
        1335.51201271, 11488.12672871, 28433.56921835,  9579.84064364,
        5433.56346148, 38652.77389498, 40489.65609559, 37368.65470995,
       15284.92662792, 36198.30811751,  9347.98512607, 31860.48444087,
        4038.5564809 , 10177.0679101 ,  2351.74502426,  7033.06024072,
       11582.7272849 , 13039.72835928, 14522.20459751,  6350.04697099,
       10154.40876381,  2293.16703391,  9244.04543239, 13257.95281229,
        4614.29814543,  3761.44571823,  4483.8771309 , 12981.54151194,
        2045.54202618,  8881.06507508, 33752.74059786, 32864.84438254,
        4014.99675554,  4450.33228534, 14154.83233701, 11707.26816402,
        8882.1515815 , 12240.14662736,  5389.17533091,  3296.47990632,
       35818.82498723,  9213.85324687, 15971.82090458,  2489.956274  ,
       12383.69562051,  1568.83224064, 13534.38002882, 12689.24282344,
        4467.9388667 , 32481.02953475, 13358.91917169, 12963.93257162,
       14237.30112536, 10497.19548192, 16419.68185284,  8052.18688859,
       11939.27105474,  4281.1317697 , 26962.27815852, 11244.00064813,
        2400.88152358,  6062.06567513, 10722.64216302, 11731.47585931,
       11123.19200122,  9340.14826239, 12035.46281216,  6911.13873796,
        7319.87941355, 11008.94841901,  6717.68264651,  8936.49798002,
        3839.86509734, 36994.59974894,  6439.8058857 , 30998.62256301,
       34832.34099697, 35534.09600266,  7201.91253041, 13026.33932462,
       10148.14842232, 14505.20184678, 17749.75425174, 35769.28453691,
       33382.92456953,  6321.14278038, 32263.71024677,  9529.29527435,
       29806.88975999,  3752.34535292, 28781.61845831,  6030.95926134,
        5595.84907761,  1887.2565521 , 11521.07147083, 15122.44575724,
       11929.23979311,  4368.35600281, 10105.76179323, 32223.17177604,
          69.01221704, 33324.80339259,  3221.6728575 , 10094.40870043,
       14430.57129034, 31877.2336075 , 11575.20059579,  3893.78029755,
       13261.43831332, 32121.35770084,  8343.87753224,  3424.21948423,
        8479.31517866, 10742.96637623, 15247.10777628,  5692.80857312,
        4052.62295799, 10394.46828184, 11015.1072666 , 11250.31010816,
       14579.61698493,  7382.64409144,  5554.37632262,  9385.18623393,
        9455.29229259, 12510.6091299 ,  8332.76336028, 15333.22336776,
        8398.96343081, 32016.59130208, 36007.22029259, 31843.39263162,
        6217.91547145, 12659.29813675,  6069.93699409, 14686.99057194,
        2691.63739506, 33304.82120386,  6494.18001765,  5065.0622803 ,
       14505.12026021,  6979.99984987, 39003.49599358,  3243.01305773,
        5837.31746562, 31890.48869511, 11589.32403507,  8474.75921847,
       14912.84991224, 10032.730397  , 27354.7780737 , 33690.58930088,
       14691.79962919,  1884.88965381, 13370.09105507,  2345.72261376,
        5465.2228474 , 11677.9161097 , 39964.69297431, 36870.1312445 ,
       34269.2495987 ,  3895.01355813,  7666.86714319,  8680.98448246,
       12343.11535453,  5040.66865853,  2085.64632064, 32564.46990864,
       25308.25562661, 17559.24051922, 26957.9016678 , 10472.57276846,
       37609.5460276 ,  -188.78161036,  7141.04984646,  7770.38297941,
        4594.26522931,  5185.93173191,  6000.14858194,  4354.54136987,
       15171.74852298, 11373.47644147,  6882.88302009,  2567.11131029,
        1676.56015643, 32082.26304328, 16508.72351622, 12149.6241888 ,
        1486.97821897, 12705.1450235 ,  1648.85415299,  8866.8752153 ,
        2123.62325665, 34329.74750397, 10832.80575656,  2800.70180616,
       26038.93931706, 26736.80149856,  9678.32891104,  2114.38797201,
       13301.76050035,  1279.03613742, 10608.21600228, 10890.56887666,
       16812.4987964 , 27202.82110157,  7225.01469226,  5282.5665049 ,
        6046.05428615, 13539.67550662, 11401.23828529,  8478.78995752,
        5172.80437231, 12345.62851994, 13838.08765137, 36047.33379894,
        4250.32109031, 29210.25872113,  -786.96604637,  2982.24228239,
       11264.36353085, 15784.82962106,  5233.44045461,  7263.02657059,
        3986.04766062, 31567.20843485,  7614.29950544, 12497.96258996,
        5779.95807258,  9511.15439104, 36550.96293901,  4500.52555285,
        9974.51731555, 31305.61221001,  5812.68181395,  4761.54631707,
        1237.5536835 ,  4951.41567577,  4660.9673735 ,  6523.8536863 ,
       18709.24325596, -1241.74064123,  2372.24061688, 10713.5338563 ,
        3223.47549342, 10451.12710651,  3843.83825606,  5246.37068861,
       12505.78776748,  6314.55260339,  8448.57030075,  7703.08447653,
        9171.90652516, 10836.97306291, 28135.65690271, 39389.59802414,
       12017.58000781,  7814.82783155, 41042.82630411, 12342.08345134])

In [22]:
mse = mean_squared_error(y_test, y_pred)
mse

33638710.48270799

In [24]:
mae = mean_absolute_error(y_test, y_pred)
mae

4186.562998121063

In [23]:
r2 = r2_score(y_test, y_pred)
r2

0.7833237659369185

In [28]:
import pickle
with open("Medical Cost LinearRegression.pkl", "wb") as file:
    pickle.dump((lr, le), file)